version: '3.8'

services:
    db:
        image: postgres:10.7
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: eatuntil
            POSTGRES_USER: eatuntil
            POSTGRES_PASSWORD: eatuntil
