# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  yarn_install:
    steps:
      - restore_cache:
          key: yarn_install-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn_install-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

jobs:
  yarn-install:
    docker:
      - image: circleci/node:12.18.3
    working_directory: ~/project/app
    steps:
      - checkout:
          path: ~/project
      - yarn_install
      - persist_to_workspace:
          root: ~/project
          paths:
            - app/node_modules
  lint:
    docker:
      - image: circleci/node:12.18.3
    working_directory: ~/project/
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - run: yarn lint:js

workflows:
  version: 2
  build:
    jobs:
      - yarn-install
      - lint:
          requires:
            - yarn-install
