version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  yarn-install:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn

  lint:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
          name: Run lint
          command: yarn lint:js

  build:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
          name: Run build
          command: yarn build

workflows:
  build:
    jobs:
      - yarn-install
      - lint:
          requires:
          - yarn-install
      - build:
          requires:
          - lint
