version: 2.1

orbs:
  node: circleci/node@4.1

jobs:

  lint:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run lint
          command: yarn lint:js

  build:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
          name: Run lint
          command: yarn build

workflows:
  build:
    jobs:
      - lint
      - build:
          requires:
          - lint
