version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  yarn-install:
    docker:
      - image: cimg/node:15.1
    working_directory: /tmp/workspace
    steps:
      - checkout:
          path: /tmp/workspace
      - node/install-packages:
          pkg-manager: yarn
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - node_modules

  lint:
    docker:
      - image: cimg/node:15.1
    working_directory: /tmp/workspace
    steps:
      - checkout:
          path: /tmp/workspace
      - run:
          name: Run lint
          command: yarn lint:js

  build:
    docker:
      - image: cimg/node:15.1
    working_directory: /tmp/workspace
    steps:
      - checkout
      - run:
          name: Run build
          command: yarn build

workflows:
  build:
    jobs:
      - yarn-install
      - lint:
          requires:
          - yarn-install
      - build:
          requires:
          - lint
